"""Provider-neutral value objects for one conversational turn."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass(frozen=True, slots=True)
class ToolDefinition:
    """A deliberately small representation of an approved MCP tool."""

    name: str
    description: str
    input_schema: Mapping[str, Any]


@dataclass(frozen=True, slots=True)
class ToolCall:
    """An untrusted tool request generated by a model."""

    name: str
    arguments: Mapping[str, Any]
    call_id: str | None = None


@dataclass(frozen=True, slots=True)
class ToolResult:
    """Structured application data returned over the tool-response channel."""

    name: str
    result: Mapping[str, Any]


@dataclass(frozen=True, slots=True)
class ModelTurn:
    """All non-secret context given to a provider for one user turn."""

    user_message: str
    system_instruction: str
    current_time: datetime
    tools: tuple[ToolDefinition, ...]


@dataclass(frozen=True, slots=True)
class ModelDecision:
    """Either a plain-text answer or a request to invoke one tool."""

    text: str | None = None
    tool_call: ToolCall | None = None

    def __post_init__(self) -> None:
        if (self.text is None) == (self.tool_call is None):
            raise ValueError("a model decision must contain exactly one outcome")
